# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: ko
title: First Blog
email: shlrur123@gmail.com
description: A blog about study log.
baseurl: # the optional subpath of your site, e.g. "/blog"
url: "https://shlrur.github.io/"
author: 
  name: Heekyum
  twitter:
  picture:
twitter_username:
github_username: shlrur
instagram_username: dochaebi

logo: "/assets/images/me.jpg"

search: false
search_full_content: false # true, false (default)
search_provider: algolia
algolia:
  application_id: 8K2C62GHZZ
  index_name: my_first_blog_search
  search_only_api_key: ac6b1c9d2ea0e17891c512e13491b27b
  powered_by: # true (default), false

disqus:
  shortname: shlrurs-blog

google_analytics: UA-128564894-1

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
feed:
  path: atom.xml

# Pagination configuration (used by the `blog` layout)
pagination:
  enabled:           true
  per_page:          5
  limit:             0
  sort_field:        "date"
  sort_reverse:      true

permalink: pretty

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Basically Basic sample site
  - /example # ignore Basically Basic dev site
